import {
  BookOpen,
  Code,
  Calculator,
  FlaskConical,
  PenTool,
  Music,
  Globe,
  Dumbbell,
  Briefcase,
  Coffee,
  Gamepad2,
  Palette,
  Microscope,
  Languages,
  Brain,
  Laptop,
  Leaf,
  Atom,
  History,
  Scale,
  Stethoscope,
  Megaphone,
  Camera,
  Video,
  Headphones,
  Utensils,
  Plane,
  Home,
  Wallet,
  Heart,
  Star,
  Zap,
  Anchor,
  Feather,
  Key,
  Map,
  Sun,
  Moon,
  Cloud,
  Umbrella,
  LucideIcon
} from "lucide-react";

export const SUBJECT_ICONS: { [key: string]: LucideIcon } = {
  "book": BookOpen,
  "code": Code,
  "math": Calculator,
  "science": FlaskConical,
  "writing": PenTool,
  "music": Music,
  "language": Languages,
  "gym": Dumbbell,
  "work": Briefcase,
  "break": Coffee,
  "game": Gamepad2,
  "art": Palette,
  "biology": Microscope,
  "geography": Globe,
  "psychology": Brain,
  "tech": Laptop,
  "nature": Leaf,
  "physics": Atom,
  "history": History,
  "law": Scale,
  "medicine": Stethoscope,
  "marketing": Megaphone,
  "photo": Camera,
  "video": Video,
  "audio": Headphones,
  "food": Utensils,
  "travel": Plane,
  "home": Home,
  "finance": Wallet,
  "health": Heart,
  "star": Star,
  "energy": Zap,
  "sea": Anchor,
  "soft": Feather,
  "security": Key,
  "explore": Map,
  "day": Sun,
  "night": Moon,
  "weather": Cloud,
  "rain": Umbrella
};

export const DEFAULT_ICON = "book";
